name: Generate Manifest

on:
  workflow_dispatch:

  push:
    branches:
      - master
    paths:
      - '**.lua'

env:
  MODULES: |-
    control
    core
    mine
    render
    turtle

jobs:
  manifest:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Generate Manifest
      run: |-
        for module in $MODULES do
          echo $module
          # cd $GITHUB_WORKSPACE/${module}
          # bash $GITHUB_WORKSPACE/.bin/manifest.sh
        done

    # - name: Commit Changes
    #   run: |-
    #     git config user.name github-actions
    #     git config user.email github-actions@github.com
    #     git add $GITHUB_WORKSPACE/control/manifest.json
    #     git add $GITHUB_WORKSPACE/control/manifest.json
    #     git add $GITHUB_WORKSPACE/core/manifest.json
    #     git add $GITHUB_WORKSPACE/mine/manifest.json
    #     git add $GITHUB_WORKSPACE/turtle/manifest.json
    #     git commit -m "Generate new manifest"
    #     git push
